apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainappdep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trainapp
  template:
    metadata:
      name: trainapppod
      labels:
        app: trainapp
    spec:
      containers:
      - name: trainappcontainer
        image: jk2425/trainticket:IMAGE_TAG
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: trainapp
spec:
  selector:
    app: trainapp
  ports:
  - port: 80
    targetPort: 8081
    NodePort: 32159
  type: NodePort
